/oak:
  ros__parameters:
    driver:
      i_calibration_dump: false
      i_device_id: ''
      i_enable_ir: true
      i_external_calibration_path: ''
      i_ip: ''
      i_pipeline_auto_calibration_mode: ''
      i_pipeline_dump: false
      i_publish_tf_from_calibration: true
      i_restart_on_diagnostics_error: false
      i_rs_compat: false
      i_tf_base_frame: oak
      i_tf_cam_pitch: '0.0'
      i_tf_cam_pos_x: '0.0'
      i_tf_cam_pos_y: '0.0'
      i_tf_cam_pos_z: '0.0'
      i_tf_cam_roll: '0.0'
      i_tf_cam_yaw: '0.0'
      i_tf_custom_urdf_location: ''
      i_tf_custom_xacro_args: ''
      i_tf_device_model: ''
      i_tf_device_name: oak
      i_tf_imu_from_descr: 'false'
      i_tf_parent_frame: oak_parent_frame
      i_usb_port_id: ''
      i_usb_speed: SUPER
      r_floodlight_intensity: 0.6000000238418579
      r_laser_dot_intensity: 0.6000000238418579
    imu:
      i_acc_cov: 0.0
      i_acc_freq: 480
      i_acc_mode: ACCELEROMETER_RAW
      i_batch_report_threshold: 5
      i_enable_acc: true
      i_enable_gyro: true
      i_enable_mag: true
      i_enable_rotation: true
      i_get_base_device_timestamp: false
      i_gyro_cov: 0.0
      i_gyro_freq: 400
      i_gyro_mode: GYROSCOPE_RAW
      i_mag_cov: 0.0
      i_mag_freq: 100
      i_mag_mode: MAGNETOMETER_RAW
      i_max_batch_reports: 10
      i_max_q_size: 8
      i_message_type: IMU
      i_rot_cov: 0.0
      i_rot_freq: 400
      i_rot_mode: ROTATION_VECTOR
      i_sync_method: COPY
      i_update_ros_base_time_on_ros_msg: false
    left:
      i_add_exposure_offset: false
      i_board_socket_id: 1
      i_calibration_file: ''
      i_disable_node: false
      i_enable_feature_tracker: false
      i_enable_lazy_publisher: true
      i_enable_nn: false
      i_exposure_offset: 0
      i_fps: 10.0
      i_fsync_continuous: false
      i_fsync_trigger: false
      i_get_base_device_timestamp: false
      i_height: 400
      i_low_bandwidth: false
      i_low_bandwidth_bitrate: 0
      i_low_bandwidth_ffmpeg_encoder: libx264
      i_low_bandwidth_frame_freq: 30
      i_low_bandwidth_profile: 4
      i_low_bandwidth_quality: 50
      i_max_q_size: 8
      i_publish_compressed: false
      i_publish_full_resolution: false
      i_publish_topic: false
      i_resize_mode: CROP
      i_reverse_stereo_socket_order: false
      i_simulate_from_topic: false
      i_simulated_topic_name: ''
      i_synced: false
      i_undistorted: true
      i_update_ros_base_time_on_ros_msg: false
      i_use_max_resolution_possible: false
      i_width: 640
      r_auto_exp_region_height: 0
      r_auto_exp_region_start_x: 0
      r_auto_exp_region_start_y: 0
      r_auto_exp_region_width: 0
      r_auto_exposure_limit: 1000
      r_chroma_denoise: 1
      r_exposure: 1000
      r_iso: 800
      r_luma_denoise: 1
      r_set_auto_exp_region: false
      r_set_auto_exposure_limit: false
      r_set_chroma_denoise: false
      r_set_luma_denoise: false
      r_set_man_exposure: false
      r_set_man_focus: false
      r_set_man_whitebalance: false
      r_set_sharpness: false
      r_sharpness: 1
    oak:
      rgb:
        image_raw:
          compressed:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
          compressedDepth:
            depth_max: 10.0
            depth_quantization: 100.0
            format: png
            png_level: 3
          depth_max: 10.0
          depth_quantization: 100.0
          enable_pub_plugins:
          - image_transport/compressedDepth
          - image_transport/compressed
          - image_transport/raw
          - image_transport/theora
          - image_transport/zstd
          format: jpeg
          jpeg_quality: 95
          keyframe_frequency: 64
          optimize_for: true
          png_level: 3
          quality: 31
          target_bitrate: 800000
          theora:
            keyframe_frequency: 64
            optimize_for: true
            quality: 31
            target_bitrate: 800000
          tiff:
            res_unit: inch
            xdpi: -1
            ydpi: -1
          zstd:
            zstd_level: 3
      stereo:
        image_raw:
          compressed:
            format: jpeg
            jpeg_quality: 95
            png_level: 3
            tiff:
              res_unit: inch
              xdpi: -1
              ydpi: -1
          compressedDepth:
            depth_max: 10.0
            depth_quantization: 100.0
            format: png
            png_level: 3
          depth_max: 10.0
          depth_quantization: 100.0
          enable_pub_plugins:
          - image_transport/compressedDepth
          - image_transport/compressed
          - image_transport/raw
          - image_transport/theora
          - image_transport/zstd
          format: jpeg
          jpeg_quality: 95
          keyframe_frequency: 64
          optimize_for: true
          png_level: 3
          quality: 31
          target_bitrate: 800000
          theora:
            keyframe_frequency: 64
            optimize_for: true
            quality: 31
            target_bitrate: 800000
          tiff:
            res_unit: inch
            xdpi: -1
            ydpi: -1
          zstd:
            zstd_level: 3
    pipeline_gen:
      i_enable_diagnostics: false
      i_enable_imu: true
      i_enable_rgbd: true
      i_enable_vio: true
      i_nn_type: none
      i_pipeline_type: rgbd
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf_static:
        publisher:
          depth: 1
          history: keep_last
          reliability: reliable
    rgb:
      i_add_exposure_offset: false
      i_board_socket_id: 0
      i_calibration_file: ''
      i_disable_node: false
      i_enable_feature_tracker: false
      i_enable_lazy_publisher: true
      i_enable_nn: false
      i_exposure_offset: 0
      i_fps: 10.0
      i_fsync_continuous: false
      i_fsync_trigger: false
      i_get_base_device_timestamp: false
      i_height: 400
      i_low_bandwidth: false
      i_low_bandwidth_bitrate: 0
      i_low_bandwidth_ffmpeg_encoder: libx264
      i_low_bandwidth_frame_freq: 30
      i_low_bandwidth_profile: 4
      i_low_bandwidth_quality: 50
      i_max_q_size: 8
      i_publish_compressed: false
      i_publish_full_resolution: false
      i_publish_topic: true
      i_resize_mode: CROP
      i_reverse_stereo_socket_order: false
      i_simulate_from_topic: false
      i_simulated_topic_name: ''
      i_synced: true # set to true to ensure rgb and depth are synchronized for reconstruction
      i_undistorted: true
      i_update_ros_base_time_on_ros_msg: false
      i_use_max_resolution_possible: false
      i_width: 640
      r_auto_exp_region_height: 0
      r_auto_exp_region_start_x: 0
      r_auto_exp_region_start_y: 0
      r_auto_exp_region_width: 0
      r_auto_exposure_limit: 1000
      r_chroma_denoise: 1
      r_exposure: 1000
      r_iso: 800
      r_luma_denoise: 1
      r_set_auto_exp_region: false
      r_set_auto_exposure_limit: false
      r_set_chroma_denoise: false
      r_set_luma_denoise: false
      r_set_man_exposure: false
      r_set_man_focus: false
      r_set_man_whitebalance: false
      r_set_sharpness: false
      r_sharpness: 1
    rgbd:
      i_board_socket_id: 0
      i_get_base_device_timestamp: false
      i_max_q_size: 10 # increase if messages are being dropped in the pipeline
      i_num_threads: 1
      i_publish_topic: true
      i_run_align_on_host: true
      i_run_sync_on_host: true
      i_update_ros_base_time_on_ros_msg: false
    right:
      i_add_exposure_offset: false
      i_board_socket_id: 2
      i_calibration_file: ''
      i_disable_node: false
      i_enable_feature_tracker: false
      i_enable_lazy_publisher: true
      i_enable_nn: false
      i_exposure_offset: 0
      i_fps: 10.0
      i_fsync_continuous: false
      i_fsync_trigger: false
      i_get_base_device_timestamp: false
      i_height: 400
      i_low_bandwidth: false
      i_low_bandwidth_bitrate: 0
      i_low_bandwidth_ffmpeg_encoder: libx264
      i_low_bandwidth_frame_freq: 30
      i_low_bandwidth_profile: 4
      i_low_bandwidth_quality: 50
      i_max_q_size: 8
      i_publish_compressed: false
      i_publish_full_resolution: false
      i_publish_topic: false
      i_resize_mode: CROP
      i_reverse_stereo_socket_order: false
      i_simulate_from_topic: false
      i_simulated_topic_name: ''
      i_synced: false
      i_undistorted: true
      i_update_ros_base_time_on_ros_msg: false
      i_use_max_resolution_possible: false
      i_width: 640
      r_auto_exp_region_height: 0
      r_auto_exp_region_start_x: 0
      r_auto_exp_region_start_y: 0
      r_auto_exp_region_width: 0
      r_auto_exposure_limit: 1000
      r_chroma_denoise: 1
      r_exposure: 1000
      r_iso: 800
      r_luma_denoise: 1
      r_set_auto_exp_region: false
      r_set_auto_exposure_limit: false
      r_set_chroma_denoise: false
      r_set_luma_denoise: false
      r_set_man_exposure: false
      r_set_man_focus: false
      r_set_man_whitebalance: false
      r_set_sharpness: false
      r_sharpness: 1
    start_type_description_service: true
    stereo:
      i_add_exposure_offset: false
      i_aligned: true
      i_bilateral_sigma: 0
      i_board_socket_id: 0
      i_calibration_file: ''
      i_depth_preset: DEFAULT
      i_disparity_width: DISPARITY_96
      i_enable_alpha_scaling: false
      i_enable_brightness_filter: false
      i_enable_companding: false
      i_enable_decimation_filter: false
      i_enable_disparity_shift: false
      i_enable_distortion_correction: true
      i_enable_lazy_publisher: true
      i_enable_left_rgbd: false
      i_enable_left_spatial_nn: false
      i_enable_right_rgbd: false
      i_enable_right_spatial_nn: false
      i_enable_spatial_filter: false
      i_enable_speckle_filter: false
      i_enable_temporal_filter: false
      i_enable_threshold_filter: false
      i_exposure_offset: 0
      i_extended_disp: false
      i_fps: 10.0
      i_get_base_device_timestamp: false
      i_height: 400
      i_left_rect_add_exposure_offset: false
      i_left_rect_enable_feature_tracker: false
      i_left_rect_exposure_offset: 0
      i_left_rect_low_bandwidth: false
      i_left_rect_low_bandwidth_bitrate: 0
      i_left_rect_low_bandwidth_ffmpeg_encoder: libx264
      i_left_rect_low_bandwidth_frame_freq: 30
      i_left_rect_low_bandwidth_profile: 4
      i_left_rect_low_bandwidth_quality: 50
      i_left_rect_publish_compressed: false
      i_left_rect_publish_topic: false
      i_left_rect_synced: false
      i_left_socket_id: 1
      i_low_bandwidth: false
      i_low_bandwidth_bitrate: 0
      i_low_bandwidth_ffmpeg_encoder: libx264
      i_low_bandwidth_frame_freq: 30
      i_low_bandwidth_profile: 4
      i_low_bandwidth_quality: 50
      i_lr_check: true
      i_lrc_threshold: 10
      i_max_q_size: 8
      i_output_disparity: false
      i_publish_compressed: false
      i_publish_topic: true
      i_rectify_edge_fill_color: 0
      i_reverse_stereo_socket_order: false
      i_right_rect_add_exposure_offset: false
      i_right_rect_enable_feature_tracker: false
      i_right_rect_exposure_offset: 0
      i_right_rect_low_bandwidth: false
      i_right_rect_low_bandwidth_bitrate: 0
      i_right_rect_low_bandwidth_ffmpeg_encoder: libx264
      i_right_rect_low_bandwidth_frame_freq: 30
      i_right_rect_low_bandwidth_profile: 4
      i_right_rect_low_bandwidth_quality: 50
      i_right_rect_publish_compressed: false
      i_right_rect_publish_topic: false
      i_right_rect_synced: false
      i_right_socket_id: 2
      i_run_align_on_host: true
      i_set_disparity_to_depth_use_spec_translation: false
      i_set_input_size: false
      i_socket_name: rgb
      i_stereo_conf_threshold: 15
      i_subpixel: true
      i_subpixel_fractional_bits: 3
      i_synced: true # set to true to ensure rgb and depth are synchronized for reconstruction
      i_update_ros_base_time_on_ros_msg: false
      i_use_neural_depth: false
      i_width: 640
    use_sim_time: false